services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
      - key: N8N_BASIC_AUTH_USER
      - key: N8N_BASIC_AUTH_PASSWORD
      - key: WEBHOOK_URL
      - key: N8N_HOST
      - key: N8N_PORT

